require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pdfs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Pdf. As you add validations to Pdf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pdf.create! valid_attributes
      get pdfs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pdf = Pdf.create! valid_attributes
      get pdf_url(pdf)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pdf_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pdf = Pdf.create! valid_attributes
      get edit_pdf_url(pdf)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pdf" do
        expect {
          post pdfs_url, params: { pdf: valid_attributes }
        }.to change(Pdf, :count).by(1)
      end

      it "redirects to the created pdf" do
        post pdfs_url, params: { pdf: valid_attributes }
        expect(response).to redirect_to(pdf_url(Pdf.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pdf" do
        expect {
          post pdfs_url, params: { pdf: invalid_attributes }
        }.to change(Pdf, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pdfs_url, params: { pdf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pdf" do
        pdf = Pdf.create! valid_attributes
        patch pdf_url(pdf), params: { pdf: new_attributes }
        pdf.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pdf" do
        pdf = Pdf.create! valid_attributes
        patch pdf_url(pdf), params: { pdf: new_attributes }
        pdf.reload
        expect(response).to redirect_to(pdf_url(pdf))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pdf = Pdf.create! valid_attributes
        patch pdf_url(pdf), params: { pdf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pdf" do
      pdf = Pdf.create! valid_attributes
      expect {
        delete pdf_url(pdf)
      }.to change(Pdf, :count).by(-1)
    end

    it "redirects to the pdfs list" do
      pdf = Pdf.create! valid_attributes
      delete pdf_url(pdf)
      expect(response).to redirect_to(pdfs_url)
    end
  end
end
